"""empty message

Revision ID: 1a54c4cacbe
Revises: 3a21136bc02
Create Date: 2015-03-24 09:43:16.705741

"""

# revision identifiers, used by Alembic.
revision = '1a54c4cacbe'
down_revision = '3a21136bc02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date_added', sa.Date(), nullable=True))
    op.add_column('project', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('project_log', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('project_log', sa.Column('previous_score', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_log', 'previous_score')
    op.drop_column('project_log', 'likes_count')
    op.drop_column('project', 'score')
    op.drop_column('project', 'date_added')
    ### end Alembic commands ###
