"""empty message

Revision ID: 1adb25fb025
Revises: 412c9a4503d
Create Date: 2015-03-22 14:32:38.628902

"""

# revision identifiers, used by Alembic.
revision = '1adb25fb025'
down_revision = '412c9a4503d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
