"""Fourth

Revision ID: 1df49594ea2
Revises: fd775ac1cd
Create Date: 2015-03-17 11:27:08.572559

"""

# revision identifiers, used by Alembic.
revision = '1df49594ea2'
down_revision = 'fd775ac1cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin')
    ### end Alembic commands ###
