"""empty message

Revision ID: 20180558979
Revises: d51bb5f40d
Create Date: 2015-03-18 15:20:06.935842

"""

# revision identifiers, used by Alembic.
revision = '20180558979'
down_revision = 'd51bb5f40d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('total_downloads', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'total_downloads')
    ### end Alembic commands ###
