"""empty message

Revision ID: 24d412b2e3a
Revises: 37416695c7f
Create Date: 2015-03-19 13:18:44.664925

"""

# revision identifiers, used by Alembic.
revision = '24d412b2e3a'
down_revision = '37416695c7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
