"""empty message

Revision ID: 28ee28350b5
Revises: 24d412b2e3a
Create Date: 2015-03-22 13:38:11.471577

"""

# revision identifiers, used by Alembic.
revision = '28ee28350b5'
down_revision = '24d412b2e3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('forks_count', sa.Integer(), nullable=True),
    sa.Column('starred_count', sa.Integer(), nullable=True),
    sa.Column('watchers_count', sa.Integer(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=True),
    sa.Column('last_commit', sa.DateTime(), nullable=True),
    sa.Column('open_issues_count', sa.Integer(), nullable=True),
    sa.Column('downloads_count', sa.Integer(), nullable=True),
    sa.Column('contributors_count', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('project', 'age')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_log')
    op.add_column('project', sa.Column('age', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
