"""empty message

Revision ID: 305728715b3
Revises: 2321e157a01
Create Date: 2015-03-18 10:54:04.072961

"""

# revision identifiers, used by Alembic.
revision = '305728715b3'
down_revision = '2321e157a01'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
