"""empty message

Revision ID: 34310ee0ae8
Revises: f70e276154
Create Date: 2015-03-18 10:27:09.976806

"""

# revision identifiers, used by Alembic.
revision = '34310ee0ae8'
down_revision = 'f70e276154'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
