"""empty message

Revision ID: 34e5921a662
Revises: 2c277fc68a7
Create Date: 2015-03-26 16:19:45.485446

"""

# revision identifiers, used by Alembic.
revision = '34e5921a662'
down_revision = '2c277fc68a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('pypi_stub', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'pypi_stub')
    ### end Alembic commands ###
