"""Second

Revision ID: 35b5dcf358e
Revises: 4a29dae83f4
Create Date: 2015-03-16 19:34:43.925610

"""

# revision identifiers, used by Alembic.
revision = '35b5dcf358e'
down_revision = '4a29dae83f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
