"""empty message

Revision ID: 3a21136bc02
Revises: 28ee28350b5
Create Date: 2015-03-23 10:11:10.106159

"""

# revision identifiers, used by Alembic.
revision = '3a21136bc02'
down_revision = '28ee28350b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_url')
    ### end Alembic commands ###
