"""empty message

Revision ID: 3d2b9c4adf1
Revises: 3d7384fe644
Create Date: 2015-03-24 14:28:50.978972

"""

# revision identifiers, used by Alembic.
revision = '3d2b9c4adf1'
down_revision = '3d7384fe644'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('submitted_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['submitted_by_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'submitted_by_id')
    ### end Alembic commands ###
