"""empty message

Revision ID: 412c9a4503d
Revises: 479850a20be
Create Date: 2015-03-22 14:31:53.975842

"""

# revision identifiers, used by Alembic.
revision = '412c9a4503d'
down_revision = '479850a20be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('git_url', sa.String(length=400), nullable=True))
    op.drop_column('project', 'github_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('github_url', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    op.drop_column('project', 'git_url')
    ### end Alembic commands ###
