"""empty message

Revision ID: 479850a20be
Revises: 24d412b2e3a
Create Date: 2015-03-20 15:56:07.206180

"""

# revision identifiers, used by Alembic.
revision = '479850a20be'
down_revision = '24d412b2e3a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'age')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('age', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
