"""empty message

Revision ID: 4c363bf9af2
Revises: 575dde6b846
Create Date: 2015-03-24 16:15:16.721300

"""

# revision identifiers, used by Alembic.
revision = '4c363bf9af2'
down_revision = '575dde6b846'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('admin')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('encrypted_password', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admin_pkey')
    )
    op.drop_table('admin_account')
    ### end Alembic commands ###
