"""empty message

Revision ID: 515355bb09e
Revises: 3a21136bc02
Create Date: 2015-03-23 22:02:32.799021

"""

# revision identifiers, used by Alembic.
revision = '515355bb09e'
down_revision = '3a21136bc02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date_added', sa.Date(), nullable=True))
    op.add_column('project_log', sa.Column('likes_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_log', 'likes_count')
    op.drop_column('project', 'date_added')
    ### end Alembic commands ###
