"""empty message

Revision ID: 575dde6b846
Revises: 472b0bb2ebe
Create Date: 2015-03-24 14:56:28.790901

"""

# revision identifiers, used by Alembic.
revision = '575dde6b846'
down_revision = '472b0bb2ebe'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_group_id_fkey', 'category', type_='foreignkey')
    op.drop_column('category', 'group_id')
    op.add_column('group', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'category', ['category_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'category_id')
    op.add_column('category', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('category_group_id_fkey', 'category', 'group', ['group_id'], ['id'])
    ### end Alembic commands ###
