"""empty message

Revision ID: 5794dc1a519
Revises: 4c363bf9af2
Create Date: 2015-03-25 16:50:58.925838

"""

# revision identifiers, used by Alembic.
revision = '5794dc1a519'
down_revision = '4c363bf9af2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('bitbucket_url', sa.Boolean(), nullable=True))
    op.add_column('project', sa.Column('current_version_release', sa.DateTime(), nullable=True))
    op.add_column('project', sa.Column('github_url', sa.Boolean(), nullable=True))
    op.add_column('project_log', sa.Column('current_version_release', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_log', 'current_version_release')
    op.drop_column('project', 'github_url')
    op.drop_column('project', 'current_version_release')
    op.drop_column('project', 'bitbucket_url')
    ### end Alembic commands ###
