"""empty message

Revision ID: 8cbee8ef02
Revises: None
Create Date: 2015-03-15 15:04:51.298123

"""

# revision identifiers, used by Alembic.
revision = '8cbee8ef02'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_name', sa.String(length=255), nullable=False),
    sa.Column('github_url', sa.String(length=400), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('github_url', sa.String(length=400), nullable=True),
    sa.Column('website', sa.String(length=400), nullable=True),
    sa.Column('pypi_url', sa.String(length=400), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('starred', sa.Integer(), nullable=True),
    sa.Column('watchers', sa.Integer(), nullable=True),
    sa.Column('age', sa.DateTime(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('last_commit', sa.DateTime(), nullable=True),
    sa.Column('open_issues', sa.Integer(), nullable=True),
    sa.Column('issues_url', sa.String(length=400), nullable=True),
    sa.Column('docs_url', sa.String(length=400), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=400), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('project')
    op.drop_table('category')
    op.drop_table('group')
    op.drop_table('user')
    ### end Alembic commands ###
