"""empty message

Revision ID: f70e276154
Revises: 577eef94128
Create Date: 2015-03-17 17:15:38.154530

"""

# revision identifiers, used by Alembic.
revision = 'f70e276154'
down_revision = '577eef94128'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
