"""empty message

Revision ID: fd775ac1cd
Revises: 35b5dcf358e
Create Date: 2015-03-16 19:41:32.263219

"""

# revision identifiers, used by Alembic.
revision = 'fd775ac1cd'
down_revision = '35b5dcf358e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
